/* Belegbare Modellangaben. Keine Marktdaten oder Sterbetafeln werden erfunden. */
function modellUiInit(){
 const input=(id,label,type='text',value='',hint='')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${value}">${hint?'<small class="hint">'+hint+'</small>':''}</div>`;
 const select=(id,label,options)=>`<div class="field"><label for="${id}">${label}</label><select id="${id}">${options.map(([v,l])=>'<option value="'+v+'">'+l+'</option>').join('')}</select></div>`;
 const check=(id,label)=>`<label class="toggle"><input id="${id}" type="checkbox">${label}</label>`;
 const source=(id,label)=>input(id,label,'text','','Quelle, Datenstand und angewendetes Modell dokumentieren.');
 const add=(id,html)=>$(id).insertAdjacentHTML('beforeend',html);
 add('s-substanz','<h3>Belegte Bauteilansätze</h3>'+check('hg_garage_vorhanden','Garage/Carport vorhanden und dem Objekt zugeordnet')+'<div class="grid">'+source('hg_garage_quelle','Grundlage des Garagenwerts')+source('hg_aussen_quelle','Grundlage des Außenanlagenwerts')+'</div>');
 add('s-grundlagen','<h3>Verfahrenswahl und weitere Nachweise</h3><p class="hint">Diese Angaben dokumentieren deine Prüfung. Die App prüft die Vollständigkeit, bestätigt aber nicht die Echtheit oder Eignung einer Quelle.</p><div class="grid">'+source('gewichtung_begruendung','Warum diese Verfahren und Gewichtung?')+source('pq_bw_quelle','Modell der Bewirtschaftungskosten')+source('pq_vgl_quelle','Vergleichspreis: Herkunft und Anpassungen')+'</div>'+check('pq_modell_geprueft','Datenstand, örtliche Eignung und Übereinstimmung mit dem Ableitungsmodell geprüft'));
 const basis=[['','Bitte prüfen'],['zusatz','Zusätzlich – noch nicht im Grundwert enthalten'],['enthalten','Bereits im Grundwert enthalten – kein weiterer Ansatz'],['teilweise','Teilweise enthalten – Restansatz separat begründen']];
 for(const prefix of ['pv','en'])add(prefix==='pv'?'pv_body':'en_body','<h3>Abgrenzung zum Grundwert</h3><div class="grid">'+select(prefix+'_basis','Ist der Vorteil bereits berücksichtigt?',basis)+input(prefix+'_markt_ansatz','Separater Marktansatz / Restansatz €','text','0',prefix==='en'?'Für die Energiekosten-Methode muss ein Marktansatz gesondert belegt werden.':'Nur bei teilweise enthaltenem Vorteil; kein erneuter voller Zuschlag.')+source(prefix+'_quelle','Quelle des zusätzlichen Marktansatzes')+source(prefix+'_begruendung','Begründung und Ausschluss einer Doppelzählung')+'</div>');
 add('niess_body','<h3>Umfang und belastbare Kapitalisierung</h3><div class="grid">'+select('ni_wertart','Zweck des Rechtswerts',[['','Bitte wählen'],['markt','Marktbezogene Wertminderung'],['steuer','Steuerlicher Kapitalwert – nur separates Szenario']])+select('ni_umfang','Welche Einheit ist betroffen?',[['','Bitte wählen'],['gesamt','Gesamte Immobilie'],['teil','Bestimmte Wohnung / Teilfläche']])+source('ni_rechtsgrundlage','Rechtsinhalt, betroffene Einheit und Kostenpflichten')+source('ni_kapital_quelle','Laufzeit oder Kapitalwert: Quelle und Stichtag')+'</div><p class="hint">Das Alter erzeugt keine automatische Lebenserwartung. Trage eine belegte Laufzeit oder einen geeigneten Kapitalwert ein. Steuerliche Werte werden nicht als Marktbelastung übernommen.</p><div id="ni_modell_status" class="flag"></div>');
 add('eb_body','<div class="grid">'+source('eb_begruendung','Vertrag, Laufzeit, Heimfall und verwendetes Bewertungsmodell')+'</div>');
 add('bw_body',`<h3>Prüfstatus des Beleihungsmodells</h3><div id="bw_modell_status" class="flag" role="status"></div><div id="bw_modell_korrekturen" class="flag"></div>
 <h3>Mindestzinssatz und Ertragsgrundlage</h3><div class="grid">${select('bw_nutzart','Nutzungsart / gesetzlicher Zinsaufschlag',[['wohnen','Wohnen (kein Aufschlag)'],['buero','Büro (kein Aufschlag)'],['handel','Handel (kein Aufschlag)'],['lager','Lager – 0,5 Prozentpunkte'],['logistik','Logistik – 0,5 Prozentpunkte'],['spezial','Spezialobjekt nach Anlage 3 – 0,5 Prozentpunkte'],['produktion','Produktion – 1,0 Prozentpunkte']])}${input('bw_min_offiziell','Veröffentlichter Grund-Mindestzins % (ohne Nutzungsaufschlag)')}${input('bw_zins_stand','Geltungsdatum des veröffentlichten Mindestsatzes','date')}${source('bw_zins_quelle','Amtliche Veröffentlichung des Jahres-Mindestsatzes')}${source('bw_grundlage','Grundlage der nachhaltigen Ertrags- und Sachwertansätze')}${select('bw_vermietet','Besteht eine Vermietung?',[['','Bitte wählen'],['nein','Nein'],['ja','Ja']])}${input('bw_vertragsmiete','Vertragliche Jahresnettomiete €')}${source('bw_miete_ausnahme','Begründete Ausnahme bei nachhaltiger Miete über Vertragsmiete')}</div>
 ${check('bw_erstklassig','Zinsausnahme für erstklassige Immobilie beanspruchen (max. 0,5 Prozentpunkte)')}<div class="grid">${source('bw_erstklassig_grund','Nachweis aller Voraussetzungen der Zinsausnahme')}</div>
 <h3>Einzelkosten und Modernisierungsrisiko</h3><p class="hint">Mindestens 15 % für Verwaltung, Instandhaltung und Mietausfall; zusätzliche Betriebskosten und Modernisierungsrisiko werden gesondert berücksichtigt. Höhere nachgewiesene Gesamtkosten gelten vorrangig.</p><div class="grid">${input('bw_neubau','Neubau-Herstellungskosten ohne Baunebenkosten / Außenanlagen €')}${input('bw_kosten_gesamt','Nachgewiesene jährliche Gesamtkosten €')}${input('bw_verw_satz','Aktualisierter Mindest-Verwaltungssatz je Wohneinheit €/Jahr')}${input('bw_verw_sp_anz','Kostenrelevante Garagen / Tiefgaragenplätze (0 = keine)')}${input('bw_verw_sp_satz','Mindest-Verwaltungssatz je Garage / Stellplatz €/Jahr')}${input('bw_verw','Tatsächliche jährliche Verwaltungskosten €')}${input('bw_inst','Tatsächliche jährliche Instandhaltungskosten €')}${select('bw_inst_satz','Instandhaltungs-Mindestansatz bezogen auf Herstellungskosten',[['0.5','Wohngebäude / mittlerer Standard – 0,5 %'],['0.8','Hallen / einfacher gewerblicher Standard – 0,8 %'],['0.4','Hochwertiges Büro / Handel – 0,4 %']])}${input('bw_ausfall','Jährlicher Ansatz für Mietausfall €')}${select('bw_modern_satz','Modernisierungsrisiko nach Objektart',[['','Bitte fachlich bestimmen'],['0','Kein zusätzlicher Ansatz – ausdrücklich begründen'],['0.2','Gering – 0,2 %'],['0.5','Mittel – 0,5 %'],['0.75','Hoch – 0,75 %']])}${input('bw_modern','Höherer jährlicher Modernisierungsansatz €')}${input('bw_nuk','Weitere nicht umlagefähige jährliche Betriebskosten €')}${source('bw_kosten_quelle','Einzelkostengrundlagen, Indexstand und Risikobegründung')}</div>
 ${check('bw_nachweise_geprueft','Einzelkosten, Nutzungsart und geltende Jahres-Mindestsätze geprüft')}
 <h3>Kurze Restnutzungsdauer und Freilegung</h3><div class="grid">${select('bw_kurzverfahren','Ertragsverfahren bei weniger als 30 Jahren Restnutzung',[['','Bitte bei Bedarf wählen'],['gesamt','Gesamten Reinertrag über Restnutzungsdauer kapitalisieren'],['abbruch','Gebäudeertrag + Bodenwert abzüglich Abbruch-Barwert']])}${input('bw_abbruch','Ermittelte Freilegungs- / Abbruchkosten €')}${input('bw_freilegung','Jahre bis zur Freilegung (0 = sofort)')}${source('bw_abbruch_quelle','Kosten, Zeitpunkt und Begründung, auch bei 0 €')}</div>
 <h3>Kontrollbetrachtung und Sachwertorientierung</h3>${check('bw_kontrolle','Nachhaltigkeitskontrolle bei Sachwert mehr als 20 % unter Ertragswert durchgeführt')}<div class="grid">${source('bw_kontrolle_grund','Ergebnis der Nachhaltigkeitskontrolle')}${source('bw_aussen_grund','Begründung für Außenanlagen über 5 % des Herstellungswerts')}</div>
 ${check('bw_eigennutzung','Dauerhafte Eigennutzungseignung nach § 4 Absatz 2 bestätigt')}<div class="grid">${source('bw_eigennutzung_grund','Eigennutzungseignung und nachhaltige Nachfrage')}${input('bw_vermiet_abzug','Wertminderung wegen bestehender Vermietung €')}${source('bw_mietabschlag_grund','Ermittlung der vermietungsbedingten Wertminderung')}</div>`);
 $('bw_nutzart').addEventListener('change',()=>{$('bw_nutzung').value=$('bw_nutzart').value==='wohnen'?'wohnen':'gewerbe';$('bw_nachweise_geprueft').checked=false;compute();});
 $('bw_nutzung').addEventListener('change',()=>{$('bw_nutzart').value=$('bw_nutzung').value==='wohnen'?'wohnen':'buero';$('bw_nachweise_geprueft').checked=false;compute();});
 const status=$('bw_modell_status'),adjust=$('bw_modell_korrekturen'),first=$('bw_body').querySelector('h3');status.previousElementSibling.remove();first.before(status,adjust);
 const replacements={bw_bewirt:'Kernkosten Verwaltung / Instandhaltung / Mietausfall % (mindestens 15)',ni_leben:'Belegte Restlaufzeit / verbleibende Lebensdauer Jahre',ni_kapwert:'Belegter Kapitalisierungsfaktor (0 = aus eingegebener Laufzeit)',ni_miete:'Jahresmietwert der betroffenen Einheit € (Gesamtmiete nur bei Gesamtrecht)',ni_grundst:'Vom Berechtigten getragene Grundsteuer €/Jahr',ni_zins:'Marktgerechter Kapitalisierungszins % (nicht automatisch steuerlicher Zinssatz)'};
 for(const[id,label]of Object.entries(replacements)){const el=$(id),lab=el?.closest('.field')?.querySelector('label');if(lab)lab.textContent=label;}
 $('pv_body').querySelector('.hint').textContent='Der Barwert des Stromertrags ist eine Szenariorechnung. Ein zusätzlicher Marktwertansatz benötigt eine Grundlage und darf einen bereits enthaltenen Vorteil nicht doppelt zählen.';
 $('bw_ansatz').querySelector('option[value="min"]').textContent='Ertragswert als regulärer Ausgangswert (§ 4 Absatz 1; Sachwert dient der Kontrolle)';
}
function modellStatusAnzeigen(BW){
 for(const [flag,body]of [['bw_aktiv','bw_body'],['niess_aktiv','niess_body'],['pv_aktiv','pv_body'],['en_aktiv','en_body'],['eb_aktiv','eb_body']])$(body).hidden=!$(flag).checked;
 const box=$('bw_modell_status');if(!box)return;
 const list=[...BW.hinweise,...BW.fehlend].map(x=>'<li><button type="button" onclick="appReveal($(\''+x.feld+'\'));$(\''+x.feld+'\').focus()">'+sEsc(x.text)+'</button></li>').join('');
 box.innerHTML='<b>'+(BW.status==='ok'?'Beleihungsmodell: Angaben und Nachweise vollständig':BW.status==='inaktiv'?'Beleihungsmodul nicht aktiviert':'Beleihungsmodell: Entwurf – '+(BW.status==='fehler'?'Eingaben prüfen':'Nachweise ergänzen'))+'</b>'+(list?'<ul>'+list+'</ul>':'');
 $('bw_modell_korrekturen').innerHTML=(BW.korrekturen||[]).length?'<b>Verwendete Mindestansätze / Anpassungen</b><ul>'+BW.korrekturen.map(t=>'<li>'+sEsc(t)+'</li>').join('')+'</ul>':'Keine automatischen Mindestanpassungen erforderlich.';
 if(BW.status!=='ok'&&BW.status!=='inaktiv')setT('o_beleihungswert','Entwurf: '+eur(window._R.beleihungswert));
 const ni=$('ni_modell_status');if(ni)ni.textContent=$('ni_wertart').value==='steuer'?'Separates Steuerszenario: keine Übernahme als Marktbelastung.':'Marktbelastung nur mit belegtem Rechtsinhalt und Kapitalwert.';
}

function modellBericht(esc){
 const P=window._PRUEF||{},BW=window._BW||{},D=window._MODELL_DETAIL||{};
 const fields=[['gewichtung_begruendung','Verfahrenswahl / Gewichtung'],['pq_sf_quelle','Sachwertfaktor'],['pq_bpi_quelle','Baupreisindex / Basisumrechnung'],['pq_lz_quelle','Liegenschaftszins'],['pq_miete_quelle','Mietansatz'],['pq_bw_quelle','Bewirtschaftungsmodell'],['pq_vgl_quelle','Vergleichspreis'],['hg_garage_quelle','Garagenansatz'],['hg_aussen_quelle','Außenanlagen'],['pv_basis','PV bereits berücksichtigt'],['pv_quelle','PV-Marktgrundlage'],['pv_begruendung','PV-Abgrenzung'],['en_basis','Energetik bereits berücksichtigt'],['en_quelle','Energetischer Marktansatz'],['en_begruendung','Energetische Abgrenzung'],['ni_wertart','Zweck des Rechtswerts'],['ni_umfang','Betroffener Umfang'],['ni_rechtsgrundlage','Rechtsinhalt'],['ni_kapital_quelle','Kapitalisierung / Laufzeit'],['bw_grundlage','Beleihungsgrundlagen'],['bw_zins_quelle','Jahres-Mindestzinsquelle'],['bw_zins_stand','Geltungsdatum Mindestsatz'],['bw_kosten_quelle','Einzelkostengrundlagen'],['bw_kurzverfahren','Verfahren bei kurzer Restnutzung'],['bw_abbruch_quelle','Freilegungskosten / Zeitpunkt'],['bw_kontrolle_grund','Nachhaltigkeitskontrolle'],['bw_eigennutzung_grund','Eigennutzungseignung']];
 const rows=fields.filter(([id])=>$(id)?.value?.trim()).map(([id,label])=>'<tr><td>'+label+'</td><td>'+esc($(id).value)+'</td></tr>').join('');
 let html='<h2>Begründungen, Nachweise und Modellstatus</h2><p>Dokumentierte Anwenderangaben; keine automatische Zertifizierung der Quellen oder der Bewertung.</p><table>'+rows+'</table>';
 if($('bw_aktiv').checked)html+='<p><b>Beleihungsmodell: '+(BW.status==='ok'?'Angaben und Nachweise vollständig':'Entwurf – nicht freigegeben')+'</b></p><ul>'+[...(BW.fehlend||[]),...(BW.hinweise||[])].map(h=>'<li>'+esc(h.text)+'</li>').join('')+'</ul><ul>'+(BW.korrekturen||[]).map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>';
 if($('en_aktiv').checked&&$('en_modus').value==='kosten')html+='<p>Energiekosten-Barwert (separates Szenario): '+eur(D.enKostenBarwert||0)+'. Zusätzlich verwendeter Marktansatz: '+eur(window._R.energieWert)+'.</p>';
 if($('pv_aktiv').checked)html+='<p>PV-Ertragsbarwert (Szenario): '+eur(D.pvPotential||0)+'. Zusätzlicher Ansatz nach Ausschluss einer Doppelzählung: '+eur(window._R.pvWert)+'.</p>';
 if($('niess_aktiv').checked&&$('ni_wertart').value==='steuer')html+='<p>Steuerliches Rechtswert-Szenario: '+eur(D.niSzenarioWert||0)+'. Nicht als Marktbelastung übernommen.</p>';
 return html;
}
